<?php
// $Id$

/**
 * @file
 * Hooks and callback functions for rules.module integration.
 */

/**
 * Implements hook_rules_privatemsg_message_insert().
 */
function privatemsg_rules_privatemsg_message_insert($message) {
  foreach ($message['recipients'] as $recipient) {
    rules_invoke_event('privatemsg_insert', $message['subject'], $message['body'], $message['author'], $recipient, $message['mid'], $message['thread_id']);
  }
}
?>
